name: Build and Deploy Holy Unblocker to Azure Web App

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install and build
        run: |
          npm install
          npm run build --if-present

      - name: Zip artifact for deployment
        run: zip -r release.zip ./*

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: holy-unblocker
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: holy-unblocker

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: 'Login to Azure'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AzureClientId }}
          creds: ${{ secrets.AzureClientSecret }} # Use creds instead of client-secret
          tenant-id: ${{ secrets.AzureTenantId }}
          subscription-id: ${{ secrets.AzureSubscriptionId }}
          auth-type: 'SERVICE_PRINCIPAL' # Correct casing here

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Algebra12' # Your Azure App Service name
          slot-name: 'Production'
          package: . # Adjust if necessary
